spring:
  application:
    name: speech-metric
  # Validation configuration
  mvc:
    throw-exception-if-no-handler-found: true
  validation:
    fail-fast: false  # Set to true if you want validation to stop on first error
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/speech_metrics_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
